---
title: "The Correspondence Analysis of Two Mode Networks Revisited"
author: "Omar Lizardo"
date: "`r Sys.Date()`"
---

```{r Setup}
      knitr::opts_chunk$set(include = TRUE, 
                       echo = FALSE, 
                       warning = FALSE, 
                       message = FALSE)
      library(conflicted)
      library(cowplot)
      library(ggcorrplot)
      library(ggbump)
      library(ggplot2)
      library(ggpubr)
      library(ggrepel)
      library(here)
      library(factoextra)
      library(igraph)
      library(kableExtra)
      library(networkdata)
      library(pals)
      library(patchwork)
      library(stringr)
      conflicted::conflicts_prefer(dplyr::filter)
      source(here("Functions", "reflections.R"))
      source(here("Functions", "ref.long.dat.R"))
      source(here("Functions", "SimRank.R"))
```

```{r Southern Women Data Matrix}
     A <- as.matrix(as_biadjacency_matrix(southern_women))
     p.names <- str_to_title(rownames(A))
     p.names[which(p.names == "Myrna")] <- "Myra"
     rownames(A) <- p.names
     colnames(A) <- str_replace(colnames(A), "/", "-")
     wlab <- paste("W", 1:18, sep = "")
     wlab <- paste(wlab, rownames(A), sep = " (")
     wlab <- paste(wlab, ")", sep = "")
     elab <- paste("E", 1:14, sep = "")
     elab <- paste(elab, colnames(A), sep = " (")
     elab <- paste(elab, ")", sep = "")
     rownames(A) <- wlab
     colnames(A) <- elab
     p <- ggcorrplot(t(A), colors = c("white", "white", "white"), 
                     lab = TRUE, lab_size = 6.5) 
     p <- p + theme(legend.position = "none", 
                  axis.text.y = element_text(size = 16, family = "serif"),
                  axis.text.x = element_text(size = 16, angle = 45, hjust = -0.2, family = "serif")
                  )
     p <- p + scale_x_discrete(position = "top") 
     p <- p + scale_y_discrete(limits = rev)
     jpeg(file = here("Plots", "southern-women.jpg"), width=800, height=800)
     p
     dev.off()
```

```{r Faust-Style Direct CA}
   FCA <- svd(diag(1/sqrt(rowSums(A))) %*% A %*% diag(1/sqrt(colSums(A))))
   w.r <- sqrt(sum(A)/rowSums(A))
   w.c <- sqrt(sum(A)/colSums(A))
   FCA$d <- FCA$d[2:14]
   FCA$u <- FCA$u[, 2:14]
   FCA$v <- FCA$v[, 2:14]
   #FCA$u <- FCA$u * FCA$d * w.r
   #FCA$v <- FCA$v * FCA$d * w.c
   FCA.d <- rbind(FCA$u, FCA$v)
   rownames(FCA.d) <- c(rownames(A), colnames(A))
   round(FCA.d, 3)
```

```{r Dual Projection CA}
   P.pg <- diag(1/rowSums(A)) %*% A
   rownames(P.pg) <- rownames(A) 
   P.gp <- diag(1/colSums(A)) %*% t(A)
   rownames(P.gp) <- colnames(A)
   P.pp <- P.pg %*% P.gp
   P.gg <- P.gp %*% P.pg
   CA.r <- eigen(P.pp)
   CA.c <- eigen(P.gg)
   rownames(CA.r$vectors) <- rownames(A)
   rownames(CA.c$vectors) <- colnames(A)
```

```{r Weighted Similarity CA}
   S.r <- A %*% diag(1/colSums(A)) %*% t(A)
   S.c <- t(A) %*% diag(1/rowSums(A)) %*% A
   SCA.r <- eigen(diag(nrow(A)) - (diag(1/rowSums(A)) %*% S.r))
   SCA.c <- eigen(diag(ncol(A)) - (diag(1/colSums(A)) %*% S.c))
   rownames(SCA.r$vectors) <- rownames(A)
   rownames(SCA.c$vectors) <- colnames(A)
```

```{r Dual Projection Eigenvector Scores}
   eig.r <- eigen(A %*% t(A))$vectors
   eig.c <- eigen(t(A) %*% A)$vectors
   rownames(eig.r) <- rownames(A)
   rownames(eig.c) <- colnames(A)
```

```{r Reflections Bump Charts}
   evens <- function(x) subset(x, x %% 2 == 0)
   odds <- function(x) subset(x, x %% 2 != 0)
   a <- reflections(A, iter = 26)
   p.e.r <- a$p.r[, evens(1:20)]
   g.e.r <- a$g.r[, evens(1:20)]
   b <- ref.long.dat(a = p.e.r, b = g.e.r, max.iter = 26)
   plot.dat <- b$person
   p <- ggplot(data = filter(plot.dat, n.iter < 18),
               mapping = aes(x = n.iter, y = ref, color = person))
   # geoms
   p <- p + geom_bump(linewidth = 1.1, smooth = 8)
   p <- p + geom_point(size = 5)
   p <- p + geom_text_repel(data = filter(plot.dat, n.iter == 2), 
                                    aes(x = n.iter, label = person), 
                                    size = 5, nudge_x = -3)
   p <-    p <- p + geom_text_repel(data = filter(plot.dat, n.iter == 18), 
                              aes(x = n.iter, label = person), 
                              size = 5, nudge_x = 0.01)

   # fixings
   p <- p + theme_minimal_grid(font_size = 14, line_size = 0)
   p <- p + scale_x_continuous(limits = c(-2, 20), breaks = evens(2:16))
   p <- p + labs(x = "Reflection")
   p <- p + scale_y_reverse()
   p <- p + theme(legend.position = "none",
        panel.grid.major = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 16)
        )
   set.seed(145)
   c <- sample(cols25(25), 18, replace = FALSE)
   p1 <- p + scale_color_manual(values=as.vector(c))
   png(file = here("Plots", "p-reflections.png"), width=600, height=625)
   p1
   dev.off()

   plot.dat <- b$group
   p <- ggplot(data = filter(plot.dat, n.iter < 14),
               mapping = aes(x = n.iter, y = ref, color = group))
   #geoms
   p <- p + geom_bump(linewidth = 1.1, smooth = 8)
   p <- p + geom_point(size = 5)
   p <- p + geom_text_repel(data = filter(plot.dat, n.iter == 2), 
                                    aes(x = n.iter, label = group), 
                                    size = 6, nudge_x = -1)
   p <- p + geom_text_repel(data = filter(plot.dat, n.iter == 14), 
                              aes(x = n.iter, label = group), 
                              size = 6, nudge_x = -0.01)
   #fixings
   p <- p + theme_minimal_grid(font_size = 14, line_size = 0)
   p <- p + scale_x_continuous(limits = c(1, 14), breaks = evens(2:12))
   p <- p + labs(x = "Reflection")
   p <- p + scale_y_reverse()
   p <- p + theme(legend.position = "none",
        panel.grid.major = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 16)
        )
   set.seed(145)
   c <- sample(cols25(25), 18, replace = FALSE)
   p2 <- p + scale_color_manual(values=as.vector(c))
   png(file = here("Plots", "g-reflections.png"), width=600, height=625)
   p2
   dev.off()
```

```{r CA versus Reflections Scatter}
   p.plot.dat <- data.frame(c = CA.r$vectors[, 2]*-1, 
                            r = a$p.s[, 26])
   p <- ggplot(data = p.plot.dat, aes(x = c, y = r))
   p <- p + geom_smooth(method = "lm", se=FALSE, formula = y ~ x, color = "gray")
   p <- p + geom_point(size = 3, color = "blue") 
   p <- p + geom_text_repel(aes(label = rownames(p.plot.dat)), color = "red")
   p <- p + theme_minimal() + labs(x = "First CA Dimension", y = "26th Reflection (Standardized)")
   p <- p + theme(axis.text = element_text(size = 16),
                  axis.title = element_text(size = 16))
   png(file = here("Plots", "p-ca-ref-corr.png"), width=600, height=625)
   p
   dev.off()

   g.plot.dat <- data.frame(cbind(c = CA.c$vectors[, 2]*-1, 
                                  r = a$g.s[, 26]))
   p <- ggplot(data = g.plot.dat, aes(x = c, y = r))
   p <- p + geom_smooth(method = "lm", se=FALSE, formula = y ~ x, color = "gray")
   p <- p + geom_point(size = 3, color = "red") 
   p <- p + geom_text_repel(aes(label = rownames(g.plot.dat)), 
                            color = "blue", size = 6)
   p <- p + theme_minimal() + labs(x = "First CA Dimension", y = "26th Reflection (Standardized)")
   p <- p + theme(axis.text = element_text(size = 16),
                  axis.title = element_text(size = 16))
   png(file = here("Plots", "g-ca-ref-corr.png"), width=600, height=625)
   p
   dev.off()
```

```{r CA versus Bonacich Re-ordered Affiliation Matrices}
      # Affiliation matrix plot (CA ordering)
      A.ord <- as.matrix(A[order(CA.r$vectors[, 2]), order(CA.c$vectors[, 2])])
      p <- ggcorrplot(t(A.ord)) 
      p <- p + scale_x_discrete(position = "top")
      p <- p + scale_y_discrete(limits = rev)
      p1 <- p + theme(legend.position = "none",
                               axis.text.x = element_text(hjust = -0.2))
      # Affiliation matrix plot (Bonacich ordering)
      A.ord <- as.matrix(A[order(eig.r[, 1]), order(eig.c[, 1])])
      p <- ggcorrplot(t(A.ord)) 
      p <- p + scale_x_discrete(position = "top")
      p <- p + scale_y_discrete(limits = rev)
      p2 <- p + theme(legend.position = "none",
                               axis.text.x = element_text(hjust = -0.2)) 
     # Affiliation matrix plot (Bonacich ordering)
      A.ord <- as.matrix(A[order(eig.r[, 2]), order(eig.c[, 2])])
      p <- ggcorrplot(t(A.ord)) 
      p <- p + scale_x_discrete(position = "top")
      p <- p + scale_y_discrete(limits = rev)
      p3 <- p + theme(legend.position = "none",
                               axis.text.x = element_text(hjust = -0.2)) 
      png(file = here("Plots", "ca-reord.png"), width=500, height=500)
      p1
      dev.off() 
      png(file = here("Plots", "bon-reord1.png"), width=500, height=500)
      p2
      dev.off() 
      png(file = here("Plots", "bon-reord2.png"), width=500, height=500)
      p3
      dev.off()
```

```{r Row Stochastic Matrices for CA Projections Plot}
   P.pg <- diag(1/rowSums(A)) %*% A
   rownames(P.pg) <- rownames(A) 
   P.gp <- diag(1/colSums(A)) %*% t(A)
   rownames(P.gp) <- colnames(A)
   P.pp <- P.pg %*% P.gp
   P.gg <- P.gp %*% P.pg
   rownames(P.pp) <- substr(colnames(P.pp), start = 1, stop = 3)
   rownames(P.gg) <- substr(colnames(P.gg), start = 1, stop = 3)
   P.p <- ggcorrplot(P.pp, lab = TRUE, lab_size = 5,
                     colors = c(rep("white", 3))) +
      theme(legend.position = "none", 
            axis.text.x = element_text(hjust = -0.2, size = 16),
            axis.text.y = element_text(size = 16)) + 
      scale_x_discrete(position = "top") + scale_y_discrete(limits=rev) 
   P.g <- ggcorrplot(P.gg, lab = TRUE, lab_size = 5,
                     colors = c(rep("white", 3))) +
      theme(legend.position = "none", 
            axis.text.x = element_text(hjust = -0.2, size = 16),
            axis.text.y = element_text(size = 16)) + 
      scale_x_discrete(position = "top") + scale_y_discrete(limits=rev) 
   png(file = here("Plots", "p-norm.png"), width=900, height=900)
   P.p
   dev.off() 
   png(file = here("Plots", "g-norm.png"), width=900, height=900)
   P.g
   dev.off() 
```

```{r CA Eigenvector Plot} 
      eigvec.dat.r <- data.frame(rank = rank(CA.r$vectors[,2]), 
                             value = as.numeric(CA.r$vectors[,2]),
                             lab = names(CA.r$vectors[,2]))
      eigvec.dat.c <- data.frame(rank = rank(CA.c$vectors[,2]), 
                             value = as.numeric(CA.c$vectors[,2]),
                             lab = names(CA.c$vectors[,2]))
      eigval.dat.c <- data.frame(k = 1:13, 
                             value = CA.c$values[2:14]/max(CA.c$values[2:14])) %>% 
             mutate(value = value / max(value))
      # Eigenvector plot for the people
      p <- ggscatter(eigvec.dat.r, y = "rank", x = "value", point = FALSE,
                 font.label =  10, label = "lab", repel = TRUE)
      p <- p + theme(axis.text.y = element_blank(),
                 axis.line.x = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks = element_blank(),
                 legend.position = "none")
      p <- p + labs(y = "Rank", x = "First Axis") 
      a <- p + geom_vline(xintercept = 0, linewidth = 0.5, linetype = 2, color = "gray")
      
      # Eigenvector plot for the groups
      p <- ggscatter(eigvec.dat.c, y = "rank", x = "value", point = FALSE,
                 font.label =  10, label = "lab", repel = TRUE)
      p <- p + theme(axis.text.y = element_blank(),
                 axis.line.x = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks = element_blank(),
                 plot.margin = margin(l = 100),
                 legend.position = "none")
      p <- p + labs(y = "Rank", x = "First Axis") 
      b <- p + geom_vline(xintercept = 0, linewidth = 0.5, linetype = 2, color = "gray")
      
      # Eigenvalue plot for the groups
      p <- ggscatter(eigval.dat.c, x = "k", y = "value", size = 2, color = "black")
      p <- p + labs(y = "", x = "k") 
      c <- p + theme(axis.text.x = element_blank(),
                    axis.text.y = element_text(size = 8),
                    axis.line.y = element_blank(),
                    axis.line.x = element_blank())
      b <- b + inset_element(c, left = 0.6, right = 1, bottom = 0, top = 0.45)
      png(file = here("Plots", "ca-eigvec.png"), width=1000, height=600)
      a + b + plot_annotation(tag_levels = 'a', tag_suffix = ')') & 
         theme(plot.tag = element_text(size = 20))
      dev.off() 
```

```{r CA Similarity and Correspondence Plot}
      norm.sim.r <- P.pp
      norm.sim.c <- P.gg
      diag(norm.sim.r) <- 0
      diag(norm.sim.c) <- 0
      norm.sim.r <- norm.sim.r[order(CA.r$vectors[,2]), 
                               order(CA.r$vectors[,2])]
      norm.sim.c <- norm.sim.c[order(CA.c$vectors[,2]), 
                               order(CA.c$vectors[,2])]
      
      # CA Similarity Plot (People)
      p <- ggcorrplot(norm.sim.r)
      p <- p + scale_x_discrete(position = "top")
      p <- p + scale_y_discrete(limits = rev)
      p <- p + scale_fill_gradient2(limit = c(0, max(norm.sim.r+0.02)), 
                                    low = "white", 
                                    high =  "darkred", 
                                    mid = "red", 
                                    midpoint = max(norm.sim.r)/2)
      a <- p + theme(legend.position = "none", 
                    axis.text.x = element_text(hjust = -0.2, size = 10)) 
      # CA Similarity Plot (Groups)
      p <- ggcorrplot(norm.sim.c)
      p <- p + scale_x_discrete(position = "top")
      p <- p + scale_y_discrete(limits = rev)
      p <- p + scale_fill_gradient2(limit = c(0, max(norm.sim.c+0.02)), 
                                    low = "white", 
                                    high =  "darkred", 
                                    mid = "red", 
                                    midpoint = max(norm.sim.c)/2)
      b <- p + theme(legend.position = "none", 
                     plot.margin = margin(l = 100), 
                    axis.text.x = element_text(hjust = -0.2, size = 10)) 
      
      # CA Correspondence Plot
      plot.dat <- data.frame(a = FCA.d[, 2], 
                             b = FCA.d[, 1], 
                             mode = c(rep(1, 18), rep(2, 14)))
      p <- ggplot(plot.dat, aes(y = a, x = b, color = factor(mode), label = rownames(plot.dat)))
      p <- p + geom_vline(xintercept = 0, color = "gray")
      p <- p + geom_hline(yintercept = 0, color = "gray")
      p <- p + geom_text_repel(size = 4, max.overlaps = 50)
      p <- p + theme_minimal() 
      p <- p + theme(legend.position = "none",
                     axis.text = element_text(size = 18),
                     axis.title = element_text(size = 20)
                     )
      p <- p + labs(x = "First Dimension", y = "Second Dimension")
      c <- p + scale_color_manual(values = c('red', 'blue'))
      
      plot.dat <- data.frame(a = FCA.d[, 3], 
                             b = FCA.d[, 1], 
                             mode = c(rep(1, 18), rep(2, 14)))
      p <- ggplot(plot.dat, aes(y = a, x = b, color = factor(mode), label = rownames(plot.dat)))
      p <- p + geom_vline(xintercept = 0, color = "gray")
      p <- p + geom_hline(yintercept = 0, color = "gray")
      p <- p + geom_text_repel(size = 4, max.overlaps = 50)
      p <- p + theme_minimal() 
      p <- p + theme(legend.position = "none",
                     axis.text = element_text(size = 18),
                     axis.title = element_text(size = 20)
                     )
      p <- p + labs(x = "First Dimension", y = "Third Dimension")
      d <- p + scale_color_manual(values = c('red', 'blue'))
      
      png(file = here("Plots", "ca-corr-plot.png"), width=1200, height=1200)
      (a + b) / c / d + 
         plot_annotation(tag_levels = 'a', tag_suffix = ')') & 
         theme(plot.tag = element_text(size = 26))
      dev.off()
```

```{r Bonacich Similarity and Correspondence Plot}
      norm.sim.r <- A %*% t(A)
      norm.sim.c <- t(A) %*% A
      diag(norm.sim.r) <- 0
      diag(norm.sim.c) <- 0
      norm.sim.r <- norm.sim.r[order(eig.r[, 1]), order(eig.r[ ,1])]
      norm.sim.c <- norm.sim.c[order(eig.c[, 1]), order(eig.c[ ,1])]
      # Bonacich Similarity Plot (People)
      p <- ggcorrplot(norm.sim.r)
      p <- p + scale_x_discrete(position = "top")
      p <- p + scale_y_discrete(limits = rev)
      p <- p + scale_fill_gradient2(limit = c(0, max(norm.sim.r+1)), 
                                    low = "white", 
                                    high =  "darkred", 
                                    mid = "red",  
                                    midpoint = max(norm.sim.r)/2)
      a <- p + theme(legend.position = "none",
                    axis.text.x = element_text(hjust = -0.2, size = 10)) 
      
      # Bonacich Similarity Plot (Groups)
      p <- ggcorrplot(norm.sim.c)
      p <- p + scale_x_discrete(position = "top")
      p <- p + scale_y_discrete(limits = rev)
      p <- p + scale_fill_gradient2(limit = c(0, max(norm.sim.c+1)), 
                                    low = "white", 
                                    high =  "darkred", 
                                    mid = "red",  
                                    midpoint = max(norm.sim.c)/2)
      b <- p + theme(legend.position = "none", plot.margin = margin(l = 100),
                    axis.text.x = element_text(hjust = -0.2, size = 10)) 
      
      # Bonacich Correspondence Plot
      eig.d1 <- c(eig.r[, 1], eig.c[, 1])*-1
      eig.d2 <- c(eig.r[, 2], eig.c[, 2])*-1
      plot.dat <- data.frame(eig.d1, eig.d2, mode = c(rep(1, 18), rep(2, 14)))
      p <- ggplot(plot.dat, aes(y = eig.d2, x = eig.d1, color = factor(mode), 
                                label = c(rownames(A), colnames(A))))
      p <- p + geom_vline(xintercept = 0, color = "gray")
      p <- p + geom_hline(yintercept = 0, color = "gray")
      p <- p + geom_text_repel(size = 4, max.overlaps = 50)
      p <- p + theme_minimal() 
      p <- p + theme(legend.position = "none",
                     axis.text = element_text(size = 18),
                     axis.title = element_text(size = 20)
                     )
      p <- p + labs(x = "First Dimension", y = "Second Dimension")
      c <- p + scale_color_manual(values = c('red', 'blue'))
      png(file = here("Plots", "bon-corr-plot.png"), width=1500, height=1000)
      (a + b) / (c) + 
         plot_annotation(tag_levels = 'a', tag_suffix = ')') & 
         theme(plot.tag = element_text(size = 26))
      dev.off()
```

```{r CA versus SimRank}
      res <- SimRank(A)
      Sr <- res$Sr
      Sc <- res$Sc
      s1.r <- eigen(Sr)$vectors[, 2]
      s1.c <- eigen(Sc)$vectors[, 2]
      diag(Sr) <- 0
      diag(Sc) <- 0
      Sr <- Sr[order(d1.r), order(d1.r)]
      Sc <- Sc[order(d1.c), order(d1.c)]
      rownames(Sr) <- substr(colnames(P.pp), start = 1, stop = 3)
      rownames(Sc) <- substr(colnames(P.gg), start = 1, stop = 3)
      a <- ggcorrplot(Sr, lab = TRUE, show.diag = FALSE, lab_size = 3) +
         theme(legend.position = "none", 
               axis.text.x = element_text(hjust = -0.2)) + 
         scale_x_discrete(position = "top") + scale_y_discrete(limits=rev) +
         scale_fill_gradient2(breaks = c(0, .5), limit = c(0, .5), 
                              low = "white", mid = "yellow", high = "purple")
      
      b <- ggcorrplot(Sc, lab = TRUE, show.diag = FALSE, lab_size = 3) +
         theme(legend.position = "none", 
               axis.text.x = element_text(hjust = -0.2)) + 
         scale_x_discrete(position = "top") + scale_y_discrete(limits=rev) +
         scale_fill_gradient2(breaks = c(0, .5), limit = c(0, .5), 
                              low = "white", mid = "yellow", high = "purple")
      
      dat.r <- data.frame(ca = d1.r,
                          sr = s1.r,
                          lab = rownames(A))
      dat.c <- data.frame(ca = d1.c,
                          sr = s1.c,
                          lab = colnames(A))
      cor <- round(cor(dat.r[,c("ca", "sr")])[1, 2], 2)
      
      c <- ggscatter(dat.r, x = "ca", y = "sr", font.label= 8, 
                     label = "lab", repel = TRUE, 
                     add = "reg.line", 
                     add.params = list(color = "gray80", 
                                       linewidth = 0.5, linetype = 2)) +
                     annotate("text", x = -.2, y = .3, 
                              label = paste("r = ", cor), size = 6) 
      cor <- round(cor(dat.c[,c("ca", "sr")])[1, 2], 2)
      
      d <- ggscatter(dat.c, x = "ca", y = "sr", font.label= 8, 
                     label = "lab", repel = TRUE, 
                     add = "reg.line",
                     add.params = list(color = "gray80", 
                                       linewidth = 0.5, linetype = 2)) +
                     annotate("text", x = -.2, y = .3, 
                              label = paste("r = ", cor), size = 6) 
      png(file = here("Plots", "simrank-v-ca.png"), width=1000, height=900)
      (a + c + plot_layout(widths = c(2, 1))) / (b + d + plot_layout(widths = c(2, 1))) + 
         plot_annotation(tag_levels = 'a', tag_suffix = ')') & 
         theme(plot.tag = element_text(size = 26))
      dev.off() 
```



