---
title: "Reflections as Correspondence Analysis"
author: "Omar Lizardo"
date: "`r Sys.Date()`"
---

# Setup
```{r setup}
     knitr::opts_chunk$set(include = TRUE, 
                       echo = FALSE, 
                       warning = FALSE, 
                       message = FALSE)
     library(factoextra)
     library(here)
     library(kableExtra)
```

```{r custom functions}
     source(here("Functions", "tmCA.R"))
     source(here("Functions", "reflections.R"))
     source(here("Functions", "sw.dat.R"))
     source(here("Functions", "cult.dat.R"))
     source(here("Functions", "ref.long.dat.R"))
     source(here("Functions", "bump.plot.R"))
```

# Data
```{r Southern Women HTML data table}
   kbl(sw.dat()[sort(rownames(sw.dat())), ], align = "c", format = "html") %>% 
      kable_minimal(full_width = F, font_size = 26) %>% 
      row_spec(1:18, extra_css = "border-bottom: 0px;line-height: 20px;") %>% 
      save_kable(here("southern-women.html"))
```

# Analysis
## Standard Correspondence Analysis of Two Mode Data and Correspondence Plot
```{r CA of affiliation matrix for Southern Women}
   ca.sw <- CA(sw.dat(), graph = FALSE)
   plot.dat <- data.frame(rbind(ca.sw$row$coord, ca.sw$col$coord)[, 1:2])
   plot.dat <- cbind(plot.dat, 
                     mode = c(rep(1, nrow(sw.dat())), 
                                        rep(2, ncol(sw.dat()))), 
                     names = rownames(plot.dat))
   p <- ggplot(plot.dat, aes(x = Dim.2, y = Dim.1*-1, 
                             color = factor(mode), label = names))
   p <- p + geom_vline(xintercept = 0, color = "gray")
   p <- p + geom_hline(yintercept = 0, color = "gray")
   p <- p + geom_text_repel(size = 5, max.overlaps = 50)
   p <- p + theme_minimal() 
   p <- p + theme(legend.position = "none",
                  axis.text = element_text(size = 16),
                  axis.title = element_text(size = 16)
                  )
   p <- p + labs(x = "Second Dimension", y = "First Dimension")
   p <- p + scale_color_manual(values = c('red', 'blue'))
   png(file = here("Plots", "ca-sw.png"), width=600, height=625)
   p
   dev.off()
```

```{r CA of affiliation matrix for cultural taste}
   ca.cult <- CA(cult.dat(), graph = FALSE)
   plot.dat <- data.frame(rbind(ca.cult$row$coord, ca.cult$col$coord)[, 1:2])
   n <- c(rownames(ca.cult$row$coord), rownames(ca.cult$col$coord))
   plot.dat <- cbind(plot.dat, 
                     mode = c(rep(1, nrow(cult.dat())), rep(2, ncol(cult.dat()))), 
                     names = n)
   a <- nrow(C) + 1
   p <- ggplot(plot.dat, aes(x = Dim.2, y = Dim.1*-1, 
                             color = factor(mode), label = names))
   p <- p + geom_vline(xintercept = 0, color = "gray")
   p <- p + geom_hline(yintercept = 0, color = "gray")
   p <- p + geom_text(data = plot.dat[1:nrow(cult.dat()), ], size = 1)
   p <- p + geom_text_repel(data = plot.dat[a:nrow(plot.dat), ], size = 5)
   p <- p + theme_minimal() 
   p <- p + theme(legend.position = "none",
                  axis.text = element_text(size = 16),
                  axis.title = element_text(size = 16)
                  )
   p <- p + labs(x = "Second Dimension", y = "First Dimension")
   p <- p + scale_color_manual(values = c('darkgray', 'blue'))
   png(file = here("Plots", "ca-cult.png"), width=600, height=625)
   p
   dev.off()
```

```{r Reflections Analysis}
   ref.sw <- reflections(, iter = 26)
   ref.cult <- reflections(cult.dat(), iter = 50)
   p.ref.sw <- ref.sw$p.r[, seq(2, 26, by = 2)]
   g.ref.sw <- ref.sw$g.r[, seq(2, 26, by = 2)]
   p.ref.cult <- ref.cult$p.r[, seq(2, 50, by = 2)]
   g.ref.cult <- ref.cult$g.r[, seq(2, 50, by = 2)]
   plot.dat.sw <- ref.long.dat(a = p.ref.sw, b = g.ref.sw, max.iter = 26)
   plot.dat.p.sw <- plot.dat.sw$person
   plot.dat.g.sw <- plot.dat.sw$group
   plot.dat.cult <- ref.long.dat(a = p.ref.cult, b = g.ref.cult, max.iter = 50)
   plot.dat.p.cult <- plot.dat.cult$person
   plot.dat.g.cult <- plot.dat.cult$group
```

```{r Reflections Bump Charts}
   png(file = here("Plots", "p-reflections-sw.png"), width=600, height=625)
   p <- bump.plot(plot.dat.p.sw, c = 20, rev  = 1, n.r = 0.01)
   p
   dev.off()
   png(file = here("Plots", "g-reflections-sw.png"), width=600, height=625)
   p <- bump.plot(plot.dat.g.sw, c = 16, rev  = -1, n.r = -1)
   p
   dev.off()
   png(file = here("Plots", "g-reflections-cult.png"), width=625, height=600)
   p <- bump.plot(plot.dat.g.cult, c = 46, rev  = -1, n.r = 1)
   p
   dev.off()
```


```{r}
   source(here("Functions", "eigvec.plot.R"))
   source(here("Functions", "tmCA.R"))
   #tm <- tmCA(cult.dat())
   #saveRDS(tm, file = here("tm-cult.rds"))
   tm.cult <- readRDS(file = here("tm-cult.rds"))
   tm.sw <- tmCA(sw.dat())
   #p <- eigvec.plot(tm.cult$CA.vec.c[, 2]*-1, s = 14)
```


```{r CA versus Reflections Scatter Plots}
   source(here("Functions", "scatter.line.R"))
   png(file = here("Plots", "p-ca-ref-corr-sw.png"), width=625, height=600)
   p <- scatter.line(c = tm.sw$eigvec.r[, 2], r = ref.sw$p.s[, 26], 
                     p.col = "red", t.col = "blue", ref.num = "26th")
   p
   dev.off()
   png(file = here("Plots", "g-ca-ref-corr-sw.png"), width=625, height=600)
   p <- scatter.line(c = tm.sw$eigvec.c[, 2], r = ref.sw$g.s[, 20], 
                     p.col = "red", t.col = "blue", ref.num = "20th", t.size = 4)
   p
   dev.off()
   png(file = here("Plots", "p-ca-ref-corr-cult.png"), width=625, height=600)
   p <- scatter.line(c = tm.cult$eigvec.r[, 2], r = ref.cult$p.s[, 46], 
                     p.col = "red", t.col = "blue", ref.num = "44th", t.size = 0)
   p
   dev.off()
   png(file = here("Plots", "g-ca-ref-corr-cult.png"), width=625, height=600)
   p <- scatter.line(c = tm.cult$eigvec.c[, 2]*-1, r = ref.cult$g.s[, 46], 
                     p.col = "red", t.col = "blue", ref.num = "44th")
   p
   dev.off()
```

   p.plot.dat <- data.frame(cbind(c = tm.sw$CA.vec.r[, 2], r = ref.res$p.s[, 22]))

   png(file = here("Plots", "p-ca-ref-corr.png"), width=600, height=625)
   p
   dev.off()
```

   p.plot.dat <- data.frame(cbind(c = tm.sw$ca.eigvec.c[, 2], 
                                  r = mr$g.s[, 16]))
   p <- ggplot(data = p.plot.dat, aes(x = c, y = r))
   p <- p + geom_point(size = 3, color = "red") 
   p <- p + geom_smooth(method = "lm", se=FALSE, formula = y ~ x, color = "gray")
   p <- p + geom_text_repel(aes(label = rownames(p.plot.dat)), 
                            color = "blue", size = 6)
   p <- p + theme_minimal() + labs(x = "First CA Dimension", y = "14th Reflection (Standardized)")
   p <- p + theme(axis.text = element_text(size = 16),
                  axis.title = element_text(size = 16))
   png(file = here("Plots", "g-ca-ref-corr.png"), width=600, height=625)
   p
   dev.off()
```